[project]
name = "deployer"
version = "0.1.0"
description = "Server to deploy agent-built websites"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[all]>=0.120.0",
    "loguru>=0.7.3",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.44",
]
